### ISSUE TITLE
导入项目之后运行报错呢 

### ISSUE THREAD

**Issue by code-rebooter** [myxh/CoolShopping#2]
![error](https://cloud.githubusercontent.com/assets/16337418/26137581/b77b62ba-3af5-11e7-9047-f1db252e3e09.png)

**Comment by wly1995** [comment]
这个怎么解决啊 我也有这个问题，你解决了吗？

**Comment by myxh** [comment]
这个问题在上个关闭的issue中已经说过了，weiboSDK重复了，删掉重新编译就好了。参考上个issue的解决办法，如果有需要的话，我再更新一下传上来

**Comment by scholar-yan** [comment]
这个是不是菜鸟窝的课程菜鸟团购的源码

**Comment by baiseng** [comment]
真的搞不懂，好难过

**Comment by baiseng** [comment]
我成功了，终于成功了   550595284

**Comment by cl465809880** [comment]
已经删除了weiboSDK的依赖，但是没有找到jar（已经删除了？），编译通过，但是运行依然会报错
![f10cb13350129640954aa1701553b4ae](https://user-images.githubusercontent.com/20153358/29502279-6b814f48-8661-11e7-80e8-286e6b190c6b.png)


![c62ee2d80223134c991181bad3335d22](https://user-images.githubusercontent.com/20153358/29502354-e05badea-8661-11e7-9cc9-6de1f92083aa.png)

**Comment by 1115016282** [comment]
我的也是，clean和同步是没问题的，但是编译就会出错
