### ISSUE TITLE
导入后报错了

### ISSUE THREAD

**Issue by dust365** [myxh/CoolShopping#4]
Error:Error converting bytecode to dex:
Cause: PARSE ERROR:
class name (com/sina/weibo/sdk/auth/Oauth2AccessToken) does not match path (weiboSDKCore_3.1.2/com/sina/weibo/sdk/auth/Oauth2AccessToken.class)
...while parsing weiboSDKCore_3.1.2/com/sina/weibo/sdk/auth/Oauth2AccessToken.class

**Comment by shenxiaolin** [comment]
同样的问题，怎么破？
